{%set name = "inflection" %}
{% set version = "0.5.1" %}
{%set hash_type = "sha256" %}
{% set hash_val = "1a29730d366e996aaacffb2f1f1cb9593dc38e2ddd30c91250c6dde09ea9b417" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - {{ name }}

about:
  home: http://github.com/jpvanhal/inflection
  license: MIT
  summary: 'A port of Ruby on Rails inflector to Python'

extra:
  recipe-maintainers:
    - pmlandwehr
