# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "OSwkXduktJd5DpRwwj8F+2m0M58VCSpaORL9xbAd+6s4HAhK/1gYrjCZRAY5bSHmRI767eN2zFebXl9zNo9Pj5E8x9SMwVF8T19J3nN3Ul8XTSB0sZOf2/MtLmDmRuxJYG5GZgcN15oewu4drSAHNWFOTNntJrLwt+0A0qB+mx2NTGbtZHt4hfVl6Nax08V8cwGzB7uGkonsx4IGASu/IgkltadxAVxo6qfhAH3G6L1TI3GoFaZ90C5tVDy/7gkcKQPUZlfhqHfzJa9vpGr3PqBjC9CuQrXRG49b2WwIgZQol2HQcUV6NNRLjqQO5XyAhe8Q8f1nMflII9hp6QDFqLVV3Lxo5Lh42cQYWupP5Wxt7zqrFMGA2BPcEIOSkZhM6nJWHC1m7+sZ8kmqd8ZPh5q+malQ3tPfsfzpzNApxaMO5RG8W2Jb9UzIlhrzQkZwNtxu6rga5AruLRs2G/F9BA/hvZkOO5HE+phLCxgttS2IHsbskBRHV/QlJazIwQV5gLYdqXmMYn4KK15kKhtBLOhChNRXOfZEzOwAP2DTzkVIvI28qfbqylIFJt6xXPsjukTunLRdYrB6VZypzgMuDTtyk5+R12eOBdA8lvg4uvW6hTMsrSkrkQQKUtiPaffMEpN5T8LnD7x5aIfeaqdm6/dIMdNRdLEEkjWKOsa3/Do="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
