travis:
  secure:
    BINSTAR_TOKEN: MEhihFHB/sym7vqFYpEYOT68752DmlGfougBHEuLH/XN3kOkfIQlU16xf/rHkHXTRRTCh5yQ8H90eAqalp/ZqqCcsKd5kZK+w16Fcfkz3tdE4sflPe6LMjhgiFqDkdfoJ19mVFJPElNR6Shwj8xiUnmissw4EBIpOrl1F7TPOM0aFmuEkEvfjglr7d53NkRKyUzeL+BOaMae1QviPa3KVsaZFl9n6MhvW7Qi1kWOZt+UVpdtdGRWXA6Z3GEbSXRNWW5vZWHa/WvhJxV27mwg6IdRSARowIfkPdjF3LLz+OysMHmXcuy1oX0G0XcfZTMB9yjzfbnhL3b6WhiQc/v/Z0GEl6jdgxAwczVdGRV/NMFvOlulXh41DZ6tQR+LZv+zPuw0t1XPka0+/vit5+dlxr0mJ4GcRLHAKtAjfpS7MaqWq0hTVcBqz/N4nRHkx8GDr/ojarRjCgh2XxlVDXlNszdbY16W8xA1kpcVBIUv0NRCwl5l+WBCQjCW1cPeeU+Y/8fE0PdjjHPuuO6LrJcFgRxbEietNz2GGV60qD6asXpG2CJ+Tivlx24VHPVTwD6cevXwEJuw5dV0YJfdMGBR0IcFDZOplcH/P77FGNeJOLOHEVNj/vdt1J1YH/f41FzXPrw5UFFGsnq/Zurqe31gT/2vWnobgQWpCisqeVi950E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
