travis:
  secure:
    BINSTAR_TOKEN: OSwkXduktJd5DpRwwj8F+2m0M58VCSpaORL9xbAd+6s4HAhK/1gYrjCZRAY5bSHmRI767eN2zFebXl9zNo9Pj5E8x9SMwVF8T19J3nN3Ul8XTSB0sZOf2/MtLmDmRuxJYG5GZgcN15oewu4drSAHNWFOTNntJrLwt+0A0qB+mx2NTGbtZHt4hfVl6Nax08V8cwGzB7uGkonsx4IGASu/IgkltadxAVxo6qfhAH3G6L1TI3GoFaZ90C5tVDy/7gkcKQPUZlfhqHfzJa9vpGr3PqBjC9CuQrXRG49b2WwIgZQol2HQcUV6NNRLjqQO5XyAhe8Q8f1nMflII9hp6QDFqLVV3Lxo5Lh42cQYWupP5Wxt7zqrFMGA2BPcEIOSkZhM6nJWHC1m7+sZ8kmqd8ZPh5q+malQ3tPfsfzpzNApxaMO5RG8W2Jb9UzIlhrzQkZwNtxu6rga5AruLRs2G/F9BA/hvZkOO5HE+phLCxgttS2IHsbskBRHV/QlJazIwQV5gLYdqXmMYn4KK15kKhtBLOhChNRXOfZEzOwAP2DTzkVIvI28qfbqylIFJt6xXPsjukTunLRdYrB6VZypzgMuDTtyk5+R12eOBdA8lvg4uvW6hTMsrSkrkQQKUtiPaffMEpN5T8LnD7x5aIfeaqdm6/dIMdNRdLEEkjWKOsa3/Do=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
