travis:
  secure:
    BINSTAR_TOKEN: RWRt5kE4nwjy1rOyCPmAGLHNArEB0eqwSB/WFlmr4Wi3ZRxZwaoZOeARW5HmTvPHP8dVcSrSKih5pRz22VuWAw1GsomvyqYJFbFw+Ev4jW4/xAhl0y1zmcdfnqlPKY7EEFpSjJLqxnStyJEdm8CR5PS+ChnJmvhan4ULbZB70p4h5/xO1anhWbMfvlNqBr+36wwDzoaxai1LPh/Y4bfb6VHOuaa0kEuoZx7p+rRahIlruSpgmKI2mIZ04LfhlG5B6pptSsKoS+5Iiwd+LO7m0otJ96EmsLTH3V+TRXm2x6s/InHtuZa85JaaNHByHkPeEHdgY6mUWgM9iHYov/gZjI+KIEEzbIRkJhuj3np9y7DMZFse1thBqD5IpP13I/CUIYMSpDelL7T4Etv746+Tpo/abvaNr+zLBGLvtSZRy4gKEAK9aNQQ/ehGqiJiiRLan6pqI2fCMEU8MEKYIoK0xTRDErxtGCoWKkW8jetzlT4niiSrtIlH70eGrPLePQ/oOMoiZiAQaV3Ef+5YMrpcN/+umzdDjCLDbyBpqBwQSSS/jrcArWIChpiZIiNoMauUuIPtnpAbBXQ+0MstAYY0/X0466tiT0ZNrwuDfWd7noAqEZxWyQ0s0gj8XeRSz8ZQ8qVTnvmiDwe+gFcarcQyc0R9lm2KrrxY3hxan6O6qfU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
